name: bilbil-dev-db

services:
  mysql:
    container_name: bilbil-mysql
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bilbil
      MYSQL_USER: bilbil
      MYSQL_PASSWORD: bilbil
    ports:
      - "3306:3306"
    volumes:
      - "../docs/00-table-schema.sql:/docker-entrypoint-initdb.d/00-table-schema.sql"
  redis:
    container_name: bilbil-redis
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server
